// styles.js
import {StyleSheet} from 'react-native';

export const Colors = {
  primary: '#242625',
  secondary: '#0FB245',
  background: '#F5F5F5',
  textPrimary: '#FEFFFE',
  textSecondary: '#B1B2B4',
  danger: '#FF4C4C',
  success: '#32CD32',
  blue: '#3674B5',
  white: '#FFFFFF',
  black: '#000000',
  lightGray: '#37383A',
  darkGray: '#666666',
};

export const style = StyleSheet.create({
  wrapper: {
    padding: 12,
    backgroundColor: Colors.primary,
    minHeight: '100%',
  },
  searchBar: {
    backgroundColor: Colors.lightGray,
    borderWidth: 1,
    borderColor: Colors.secondary,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingStart: 50,
    marginBottom: 10,
    color: Colors.white,
  },
  heading1: {
    fontSize: 24,
    fontWeight: 'bold',
    color: Colors.textPrimary,
    marginVertical: 10,
  },
  heading2: {
    marginVertical: 10,
    fontSize: 20,
    fontWeight: '600',
    color: Colors.textPrimary,
  },
  heading3: {
    marginVertical: 10,
    fontSize: 18,
    fontWeight: '500',
    color: Colors.textPrimary,
  },
  heading4: {
    marginVertical: 10,
    fontSize: 15,
    fontWeight: '500',
    color: Colors.textPrimary,
  },
  body: {
    fontSize: 16,
    color: Colors.primary,
  },
  smallText: {
    fontSize: 12,
    color: Colors.white,
  },
  links: {
    fontSize: 12,
    color: Colors.secondary,
  },
  caption: {
    fontSize: 14,
    color: Colors.textSecondary,
  },
  bold: {
    fontWeight: 'bold',
  },
  centerText: {
    textAlign: 'center',
  },
  alignCenter: {
    alignItems: 'center',
  },
  row: {
    display: 'flex',
    flexDirection: 'row',
  },
  column: {
    display: 'flex',
    flexDirection: 'column',
  },
  centered: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  centerRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 15,
  },
  team: {
    width: 100,
    alignItems: 'center',
  },
  noGap: {
    gap: 0,
  },
  spaceBetween: {
    display: 'flex',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
  },
  fullWidth: {
    width: '100%',
  },
  fullHeight: {
    height: '100%',
  },
  screenContainer: {
    flex: 1,
    backgroundColor: Colors.background,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  card: {
    borderRadius: 13,
    padding: 16,
    marginVertical: 5,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 6,
  },
  upcommingMatcheCard: {
    backgroundColor: Colors.darkGray,
    padding: 10,
    borderRadius: 10,
    marginVertical: 5,
    elevation: 6,
    position: 'relative',
  },
  upcommingMatchDate: {
    position: 'absolute',
    top: 10,
    left: 10,
  },
  cardContent: {
    paddingHorizontal: 25,
  },
  card: {
    borderRadius: 13,
    padding: 16,
    marginVertical: 5,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 6,
  },
  cardContent: {
    paddingHorizontal: 25,
  },
  primaryBtn: {
    backgroundColor: Colors.primary,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  secondaryBtn: {
    backgroundColor: Colors.secondary,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  dangerBtn: {
    backgroundColor: Colors.danger,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  disableBtn: {
    backgroundColor: Colors.darkGray,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  btnText: {
    color: Colors.white,
    fontWeight: 'bold',
    fontSize: 16,
  },
  liveBtn: {
    backgroundColor: Colors.danger,
    padding: 5,
    borderRadius: 10,
    width: 100,
    marginBottom: 10,
    alignSelf: 'flex-end',
  },
  blankPadding: {paddingBottom: 50},
  gap1: {gap: 4},
  gap2: {gap: 8},
  gap3: {gap: 12},
  mt1: {marginTop: 4},
  mt2: {marginTop: 8},
  mt3: {marginTop: 12},
  mt4: {marginTop: 20},
  mb1: {marginBottom: 4},
  mb2: {marginBottom: 8},
  mb3: {marginBottom: 12},
  mb4: {marginBottom: 14},
  pt1: {paddingTop: 4},
  pt2: {paddingTop: 8},
  pt3: {paddingTop: 12},
  pb1: {paddingBottom: 4},
  pb2: {paddingBottom: 8},
  pb3: {paddingBottom: 12},
  p1: {padding: 4},
  p2: {padding: 8},
  p3: {padding: 12},
  px1: {paddingHorizontal: 4},
  px2: {paddingHorizontal: 8},
  px3: {paddingHorizontal: 12},

  // custom styling
  cardsContainer: {
    height: 500,
    backgroundColor: Colors.lightGray,
    padding: 10,
    paddingBottom: 50,
    borderRadius: 10,
  },
  searchIcon: {
    position: 'absolute',
    top: 12,
    left: 10,
    zIndex: 99,
  },
  venueText: {
    borderBottomWidth: 2,
    borderBottomColor: Colors.secondary,
    marginBottom: 10,
  },
  playerImage: {
    marginHorizontal: 'auto',
    width: 300,
    height: 300,
    objectFit: 'contain',
  },
  playerCard: {
    backgroundColor: Colors.black,
    padding: 20,
    borderRadius: 20,
    marginVertical: 20,
  },
  border: {
    borderBottomWidth: 1,
    borderBottomColor: Colors.lightGray,
  },
  borderWhite: {
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
  },
  counterBtn: {
    width: 100,
    height: 100,
    backgroundColor: Colors.secondary,
    borderRadius: 100,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },

  // drop down style
  dropdown: {
    height: 50,
    backgroundColor: Colors.secondary,
    borderWidth: 0.5,
    borderRadius: 8,
    paddingHorizontal: 8,
  },
  label: {
    position: 'absolute',
    backgroundColor: 'white',
    left: 22,
    top: 8,
    zIndex: 999,
    paddingHorizontal: 8,
    fontSize: 14,
  },
  placeholderStyle: {
    fontSize: 16,
    color: 'white',
  },
  selectedTextStyle: {
    fontSize: 16,
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  inputSearchStyle: {
    height: 40,
    fontSize: 16,
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 5,
    padding: 10,
    backgroundColor: '#fff',
    color: Colors.black,
  },
  smInput: {
    backgroundColor: '#fff',
    color: Colors.black,
    fontSize: 10,
    paddingVertical: 0,
    width: '100%',
  },

  searchIcon: {
    position: 'absolute',
    top: 12,
    left: 10,
    zIndex: 99,
  },
  tabBarStyle: {
    backgroundColor: Colors.black,
    borderWidth: 2,
    borderColor: Colors.secondary,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    marginBottom: 5,
    borderBottomWidth: 0,
  },
  tabBarLabelStyle: {
    color: Colors.white,
  },
  tabBarIndicatorStyle: {
    backgroundColor: Colors.secondary,
    height: 5,
    width: 80,
    borderRadius: 10,
    marginLeft: 5,
  },
  tabScreenStyle: {
    backgroundColor: Colors.lightGray,
    padding: 10,
  },
  nameAbr: {
    width: 30,
    height: 30,
    borderRadius: 30,
    backgroundColor: Colors.white,
    textAlign: 'center',
    verticalAlign: 'middle',
    fontSize: 12,
    fontWeight: 'bold',
  },
  PName: {
    color: Colors.white,
    fontSize: 10,
  },
  teamCenter: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    marginHorizontal: 'auto',
    marginTop: 10,
    rowGap: 25,
  },
  teamBCenter: {
    marginTop: 0,
    marginBottom: 10,
  },
  lineUpField: {
    paddingVertical: 10,
    height: 700,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  playerCards: {
    borderRadius: 10,
    padding: 10,
    marginVertical: 5,
    backgroundColor: '#f9f9f9',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  playerRow: {
    width: '50%',
    marginBottom: 10,
  },
  loginHeader: {
    backgroundColor: Colors.secondary,
    height: 150,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    padding: 10,
  },
  error: {
    color: Colors.danger,
    fontSize: 12,
    marginBottom: 5,
  },
  dashboardCard: {
    backgroundColor: '#FF7A30',
    height: 150,
    borderRadius: 20,
    marginBottom: 10,
  },
  trackCard: {
    padding: 10,
    borderRadius: 20,
  },
  modalBody: {
    backgroundColor: Colors.darkGray,
    padding: 10,
    borderRadius: 20,
    marginHorizontal: 20,
    width: '100%',
  },
  table: {
    paddingRight: 50,
  },
  tData: {
    width: 400,
  },
  tHead: {
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: Colors.success,
    width: '100%',
    justifyContent: 'space-between',
  },
  th: {
    paddingVertical: 5,
    paddingHorizontal: 5,
    borderLeftWidth: 1,
    borderColor: Colors.black,
    width: 100,
  },
  thText: {
    color: Colors.black,
  },
  tRow: {
    backgroundColor: Colors.white,
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    borderBlockColor: Colors.success,
    borderBottomWidth: 1,
  },
  tdText: {
    color: Colors.black,
  },
  td: {
    paddingVertical: 5,
    paddingHorizontal: 5,
    borderLeftWidth: 1,
    borderColor: Colors.black,
    width: 100,
  },
  tableImage: {
    width: 50,
    height: 50,
  },
  imageBtn: {
    marginHorizontal: 'auto',
    borderWidth: 1,
    borderColor: Colors.success,
  },
  lineUpPlayer: {
    width: 30,
    height: 30,
    borderRadius: 50,
  },
  seperater: {
    height: '100%',
    width: 1,
    backgroundColor: Colors.black,
  },
  penality: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap:3,
    width: 110,
    flexWrap: 'wrap',
  },
  penalityCard: {
    backgroundColor: Colors.darkGray,
    padding: 25,
    borderRadius:10
  }
});
